
spring:
  h2:
    console:
      enabled: true
      
  datasource:
    url: jdbc:h2:mem:todo
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        'format_sql' : true
        